# Generated by Django 4.2.5 on 2023-12-05 16:28

from django.db import migrations, models
import socialapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=socialapp.models.avatar_upload_to, verbose_name='Аватар'),
        ),
    ]
