# Generated by Django 4.2.5 on 2023-12-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='add_by_user',
            field=models.BooleanField(default=False, verbose_name='Добавлен пользователем'),
        ),
    ]
