# Generated by Django 4.2.5 on 2024-01-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0005_alter_comment_creationdate_alter_photo_creationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creationdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
