# Generated by Django 4.2.5 on 2024-01-07 13:12

from django.db import migrations, models
import socialapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0008_alter_photo_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='link',
            field=models.ImageField(upload_to=socialapp.models.UploadToPath('wall')),
        ),
    ]
