# Generated by Django 4.2.5 on 2024-01-31 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import socialapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
                ('add_by_user', models.BooleanField(default=False, verbose_name='Добавлен пользователем')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communityname', models.CharField(max_length=100, verbose_name='Название для ссылки')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('info', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=socialapp.models.community_avatar_upload_to, verbose_name='Аватар')),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(default=None, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=500, verbose_name='Альбом фото')),
                ('link', models.ImageField(upload_to=socialapp.models.UploadToPath())),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialapp.community', verbose_name='Размещено в сообществе')),
                ('like', models.ManyToManyField(related_name='photolikers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, поставившие лайк')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('secondname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=socialapp.models.avatar_upload_to, verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Информация')),
                ('slug', models.SlugField(default=None, unique=True, verbose_name='URL')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialapp.city', verbose_name='Город')),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='socialapp.profile', verbose_name='Подписки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст записи')),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('from_community', models.BooleanField(blank=True, null=True, verbose_name='Пост от имени сообщества')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialapp.community', verbose_name='Размещено в сообществе')),
                ('like', models.ManyToManyField(related_name='postlikers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, поставившие лайк')),
                ('photo', models.ManyToManyField(to='socialapp.photo', verbose_name='Прикреплённые фото')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Communityadminstration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(verbose_name='0 - модератор, 1 - администратор, 2 - владелец')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialapp.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='admins',
            field=models.ManyToManyField(related_name='admins', through='socialapp.Communityadminstration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialapp.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='community',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialapp.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст комментария')),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('from_community', models.BooleanField(blank=True, null=True, verbose_name='Комментарий от имени сообщества')),
                ('like', models.ManyToManyField(related_name='commentlikers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, поставившие лайк')),
                ('photo', models.ManyToManyField(to='socialapp.photo', verbose_name='Прикреплённые фото')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialapp.post', verbose_name='Пост комментария')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialapp.country', verbose_name='Страна'),
        ),
    ]
