# Generated by Django 4.2.5 on 2023-11-22 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communityname', models.CharField(max_length=100, verbose_name='Название для ссылки в адресной строке [A-Za-z0-9]')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('info', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('avatar', models.CharField(blank=True, max_length=500, null=True, verbose_name='Аватар')),
                ('creationdate', models.DateField(verbose_name='Дата создания')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialapp.city', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, verbose_name='Адрес фото')),
                ('album', models.CharField(max_length=500, verbose_name='Альбом фото')),
                ('creationdate', models.DateField(verbose_name='Дата создания')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialapp.community', verbose_name='Размещено в сообществе')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст записи')),
                ('creationdate', models.DateField(verbose_name='Дата создания')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialapp.community', verbose_name='Размещено в сообществе')),
                ('photo', models.ManyToManyField(to='socialapp.photo', verbose_name='Прикреплённые фото')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(verbose_name='Роль участника в сообществе (0 - участник, 1 - администратор)')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialapp.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialapp.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(through='socialapp.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст комментария')),
                ('creationdate', models.DateField(verbose_name='Дата создания')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialapp.photo', verbose_name='Фото комментария')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialapp.post', verbose_name='Пост комментария')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialapp.country', verbose_name='Страна'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('secondname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('avatar', models.CharField(blank=True, max_length=500, null=True, verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Информация')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialapp.city', verbose_name='Город')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialapp.country', verbose_name='Страна')),
                ('following', models.ManyToManyField(blank=True, null=True, related_name='followers', to='socialapp.account', verbose_name='Подписки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
