# Generated by Django 4.2.5 on 2023-11-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(default=None, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='community',
            name='slug',
            field=models.SlugField(default=None, unique=True, verbose_name='URL'),
        ),
    ]
