# Generated by Django 4.2.5 on 2024-01-07 13:45

from django.db import migrations, models
import socialapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='link',
            field=models.ImageField(upload_to=socialapp.models.UploadToPath()),
        ),
    ]
