# Generated by Django 4.2.5 on 2023-11-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='socialapp.account', verbose_name='Подписки'),
        ),
    ]
