# Generated by Django 4.2.5 on 2024-01-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_alter_photo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creationdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
