# Generated by Django 4.2.5 on 2024-01-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_remove_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creationdate',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='creationdate',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creationdate',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
