# Generated by Django 4.2.5 on 2024-01-25 14:58

from django.db import migrations, models
import socialapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0007_photo_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=socialapp.models.community_avatar_upload_to, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='community',
            name='communityname',
            field=models.CharField(max_length=100, verbose_name='Название для ссылки'),
        ),
        migrations.AlterField(
            model_name='community',
            name='creationdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
