# Generated by Django 4.2.5 on 2024-01-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0008_alter_community_avatar_alter_community_communityname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='from_community',
            field=models.BooleanField(blank=True, null=True, verbose_name='Пост от имени сообщества'),
        ),
    ]
