# Generated by Django 4.2.5 on 2024-01-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0009_post_from_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='from_community',
            field=models.BooleanField(blank=True, null=True, verbose_name='Комментарий от имени сообщества'),
        ),
    ]
